Post: Extending material theme in Jetpack Compose.
xmartlabs/blog pull request #146
Opened 2021-04-29 20:24 UTC by mirland

TODO:
- [ ] Add links
- [ ] Add a banner image
- [ ] Code review
- [ ] Change blog date

2021-04-30 13:17 UTC, sante commented on _posts/2021-03-07-compose-themes.md
> +​
```suggestion
In this post, we'll analyze how to adapt, extend and make Metrial Theme more flexible so that it can stick to your product's style guidelines.
​
```

2021-04-30 13:17 UTC, sante commented on _posts/2021-03-07-compose-themes.md
> +Most Android applications already follow (or should be following) [Material Design Guidelines], and that's why Material created the `MaterialTheme`.
```suggestion
Most Android applications already follow (or should be following) [Material Design Guidelines], and that's why Material created `MaterialTheme`.
```

2021-04-30 13:17 UTC, sante commented on _posts/2021-03-07-compose-themes.md
> +Material has some guides to help improve that and it also allows to have consistency wit other apps on the same platform.
```suggestion
Material has some guides to help improve that and it also allows to have consistency with other apps on the same platform.
```

2021-04-30 13:17 UTC, sante commented on _posts/2021-03-07-compose-themes.md
> +Themes allow for consistency throughout our own application, especially if you define it at the beginning, just by applying minor configurations.
```suggestion
Themes allow for consistency throughout an application, especially if you define it at the beginning, just by applying minor configurations.
```

2021-04-30 13:17 UTC, sante commented on _posts/2021-03-07-compose-themes.md
> +However, we saw that the Material theme is not really all that flexible, and if designers don't stick 100% to the their guidelines, you may be in trouble as you may now have a mix of Material and oth
```suggestion
However, we saw that Material theme is not really all that flexible, and if designers don't stick 100% to the their guidelines, you may be in trouble as you may now have a mix of Material and other theme not really related to it.
```

2021-04-30 13:17 UTC, sante commented on _posts/2021-03-07-compose-themes.md
> +[The code in this blog should be useful for most application, I recommend you check the full implementation on GitHub], and adapt the general ideas to your specific use case.
```suggestion
[The code in this blog should be useful for most applications, but I recommend you check out the full implementation on GitHub], and adapt the general ideas to your specific use case.
```

2021-04-30 13:57 UTC, mirland commented on _posts/2021-03-07-compose-themes.md
> +permalink: /blog/extending-material-them-in-jetpack-compose/
```suggestion
permalink: /blog/extending-material-theme-in-jetpack-compose/
```

2021-05-04 13:35 UTC, f7deleon approved these changes

2021-05-04 13:35 UTC, f7deleon commented on _posts/2021-03-07-compose-themes.md
> +Additionally, Material already provides a theme that allows apps based on Material Design to reflect your own product’s branding and styles.
maybe avoid saying material two times in the same sentence
```suggestion
Additionally, Material already provides a theme that allows apps based on it to reflect your own product’s branding and styles.
```

2021-05-04 13:35 UTC, f7deleon commented on _posts/2021-03-07-compose-themes.md
> +However, we saw that Material theme is not really all that flexible, and if designers don't stick 100% to the their guidelines, you may be in trouble as you may now have a mix of Material and other t
```suggestion
However, we saw that Material theme lacks flexibility, and if designers don't stick 100% to the their guidelines, you may be in trouble as you may now have a mix of Material and other theme not really related to it.
```

2021-05-04 13:35 UTC, f7deleon commented on _posts/2021-03-07-compose-themes.md
> +[The code in this blog should be useful for most applications, but I recommend you check out the full implementation on GitHub], and adapt the general ideas to your specific use case.
maybe change this link to just github?
```suggestion
The code in this blog should be useful for most applications, but I recommend you check out the full implementation on [GitHub], and adapt the general ideas to your specific use case.
```

2021-05-04 13:35 UTC, f7deleon commented on _posts/2021-03-07-compose-themes.md
> +Themes are a collection of named resources that are useful all throughout a given application.
Maybe omitting the named resources since in the next line you explain that its assigns names to resources?
```suggestion
Themes are a collection of resources that are useful all throughout a given application.
```

2021-05-04 13:35 UTC, f7deleon commented on _posts/2021-03-07-compose-themes.md
> +Material does a great job, but from my point of view, it's too strict.
a suggestions both ways are ok i think
```suggestion
Material does a great job, but from my point of view, it lacks flexibility.
```

2021-05-04 17:57 UTC, bryant1410 reviewed
I send some minor comments so you can process them while I'm reading!

2021-05-04 17:57 UTC, bryant1410 commented on _posts/2021-03-07-compose-themes.md
> +title: Extending Material theme in Jetpack Compose.
```suggestion
title: Extending Material theme in Jetpack Compose
```

2021-05-04 17:57 UTC, bryant1410 commented on Gemfile.lock
> +  x86_64-linux-musl
Just trying to understand, why this?

2021-05-04 17:57 UTC, bryant1410 commented on _posts/2021-03-07-compose-themes.md
> +More information can be found in [Android's themes documentation], but themes assign semantic names like `colorPrimary` to Android resources, that can be later used as references in different places
```suggestion
More information can be found in [Android's themes documentation], but themes assign semantic names such as `colorPrimary` to Android resources, that can be later used as references in different places on the app.
```

"such as" should go for real examples. "like" is more like for figurative or related things.

2021-05-04 18:27 UTC, mirland commented on docker-compose.yml
> +    image: jekyll/jekyll:3.8
3.9 doesn't exist, so it's not working (https://hub.docker.com/r/jekyll/jekyll/tags?page=1&ordering=last_updated)

2021-05-04 18:30 UTC, mirland commented on Gemfile.lock
> +  x86_64-linux-musl
I can remove it, I tested to update some dependencies and it was added, but I have no idea. I'll ask bala

2021-05-04 18:39 UTC, mirland commented on Gemfile.lock
> +  x86_64-linux-musl
By bala https://www.moncefbelyamani.com/understanding-the-gemfile-lock-file/#platforms

2021-05-04 19:06 UTC, bryant1410 requested changes
It's hard to judge the content a lot as I'm not doing Android development these days, but it does sound good!

Important things to change:
* I'd give more context at the very beginning. Mentioning some keywords such as "Android", "mobile development", and maybe others. The rationale is the following. If you're very familiar with the things mentioned in this post, you won't struggle. However, if you're familiar with some of them (or not familiar at all), it's hard to tell what's the context of this post (e.g., Android or iOS? is it about mobile development? is it about the web?).
* Paragraphs are broken on blog-staging, for whatever reason.
* Why did you remove your author profile pic?

Less important things:
* Use contractions as much as you can. My understanding is that the blog post tone is informal. Not using contractions is quite formal.
* In many cases here I wouldn't use the future tense ("will"). Maybe revise it and change it to present tense.

Left many comments mostly regarding the wording, to make it clearer.

2021-05-04 19:11 UTC, bryant1410 commented on _posts/2021-03-07-compose-themes.md
> +If you are a Jetpack Compose user you may already know that one of its advantages is that it's easier to give your app a consistent look & feel by applying themes.
Also for context, what about adding some reference link here to Jetpack Compose?

2021-05-04 22:38 UTC, mirland commented
> It's hard to judge the content a lot as I'm not doing Android development these days, but it does sound good!

Thanks For the review! 

> Important things to change:

> I'd give more context at the very beginning. Mentioning some keywords such as "Android", "mobile development", and maybe others. The rationale is the following. If you're very familiar with the things mentioned in this post, you won't struggle. However, if you're familiar with some of them (or not familiar at all), it's hard to tell what's the context of this post (e.g., Android or iOS? is it about mobile development? is it about the web?).

It makes totally sense

> Paragraphs are broken on blog-staging, for whatever reason.
Good catch, I will check it

> Why did you remove your author profile pic?
I removed bytes, I've not removed my pic. I changed it to be consistent with xl brand

> Less important things:
Use contractions as much as you can. My understanding is that the blog post tone is informal. Not using contractions is quite formal.
In many cases here I wouldn't use the future tense ("will"). Maybe revise it and change it to present tense.
Left many comments mostly regarding the wording, to make it clearer.

:ok_hand:

2021-05-04 22:44 UTC, bryant1410 commented
> I removed bytes, I've not removed my pic. I changed it to be consistent with xl brand

Oh, I see.

And again, I'd shrink the code font size by about 2 pixels.

2021-05-04 22:48 UTC, mirland commented on _posts/2021-03-07-compose-themes.md
> +If you are a Jetpack Compose user you may already know that one of its advantages is that it's easier to give your app a consistent look & feel by applying themes.
What about something like:

```suggestion
If you have tried [Jetpack Compose], the new Android's modern toolkit for building UIs, you may already know that one of its advantages is that it's easier to give your app a consistent look & feel by applying themes.
```

?

In a few words, it add context and some documentation

2021-05-04 23:02 UTC, mirland commented on _posts/2021-03-07-compose-themes.md
> +However, we saw that Material theme lacks flexibility, and if designers don't stick 100% to their guidelines, you may be in trouble as you may now have a mix of Material and another theme not related
What this phrase try to tell is: if you use the material theme without these recommendations, you may have the material theme and a lot of separate theme components (that are not handled by your app theme) in your app. You have to mix both and it will be hard to maintain (and the code may be horrible).

> you may be in trouble as you will have to maintain multiple themes.

Your app theme will be divided into multiple themes (or worst, only the material theme and a lot of separate components in your app). However, is it clear?

2021-05-04 23:03 UTC, bryant1410 commented on _posts/2021-03-07-compose-themes.md
> +If you are a Jetpack Compose user you may already know that one of its advantages is that it's easier to give your app a consistent look & feel by applying themes.
I like it!

2021-05-04 23:03 UTC, bryant1410 commented on _posts/2021-03-07-compose-themes.md
> +If you are a Jetpack Compose user you may already know that one of its advantages is that it's easier to give your app a consistent look & feel by applying themes.
What about "building UIs" -> "building mobile user interfaces"? As it's the very first sentence.

2021-05-04 23:04 UTC, bryant1410 commented on _posts/2021-03-07-compose-themes.md
> +If you are a Jetpack Compose user you may already know that one of its advantages is that it's easier to give your app a consistent look & feel by applying themes.
Oh, and having both "new" and "modern" is redundant.

2021-05-04 23:05 UTC, mirland commented on _posts/2021-03-07-compose-themes.md
> +I will not explain the code because it's analog, you can find it on [GitHub](https://github.com/xmartlabs/gong/tree/b0b617e56403c1f499704111acad89093aa3c9d6/app/src/main/java/com/xmartlabs/gong/ui/th
I can say it's similar to the previous one. 
In this case, what's better, similar, or consistent?

2021-05-04 23:16 UTC, mirland commented on _posts/2021-03-07-compose-themes.md
> +If you are a Jetpack Compose user you may already know that one of its advantages is that it's easier to give your app a consistent look & feel by applying themes.
> building mobile user interfaces"

It's the new Android's toolkit, but it's not just jor android, it's unbundled, it's available on desktop and web (both are on alpha).
So, maybe just:

```suggestion
If you have tried [Jetpack Compose], the new Android's toolkit for building UIs, you may already know that one of its advantages is that it's easier to give your app a consistent look & feel by applying themes.
```
My point here, it applies to web and desktop, but anybody should be using it

2021-05-04 23:24 UTC, bryant1410 commented on _posts/2021-03-07-compose-themes.md
> +However, we saw that Material theme lacks flexibility, and if designers don't stick 100% to their guidelines, you may be in trouble as you may now have a mix of Material and another theme not related
Yeah. Maybe say "as you will have to maintain many separate theme components not handled directly by your app theme"?

2021-05-04 23:27 UTC, bryant1410 commented on _posts/2021-03-07-compose-themes.md
> +If you are a Jetpack Compose user you may already know that one of its advantages is that it's easier to give your app a consistent look & feel by applying themes.
maybe: "the new framework for building user interfaces for Android ([and beta for Web and Desktop]), you may ...", with a link ?

2021-05-04 23:28 UTC, bryant1410 commented on _posts/2021-03-07-compose-themes.md
> +If you are a Jetpack Compose user you may already know that one of its advantages is that it's easier to give your app a consistent look & feel by applying themes.
Also: "you may already know that one of its advantages is that it's easier to give your app a consistent look & feel by applying themes." -> "you may know it's now easier to ..."

And I personally don't like the ampersand there, I'd use and. But I'm not 100% sure.

2021-05-04 23:28 UTC, bryant1410 commented on _posts/2021-03-07-compose-themes.md
> +I will not explain the code because it's analog, you can find it on [GitHub](https://github.com/xmartlabs/gong/tree/b0b617e56403c1f499704111acad89093aa3c9d6/app/src/main/java/com/xmartlabs/gong/ui/th
"similar to the previous one"?

2021-05-05 02:22 UTC, mirland commented on _sass/_base.scss
> +  font-size: 15px !important;
> And again, I'd shrink the code font size by about 2 pixels.

I changed 3 pixels, it was the previous value before the website redesign, what do you think?

I've also changed it in the webflow css file, but I think we'll lose this change in the future

2021-05-05 02:25 UTC, bryant1410 commented on _sass/_base.scss
> +  font-size: 15px !important;
It looks better!

2021-05-05 02:26 UTC, bryant1410 approved these changes

2021-05-06 00:47 UTC, bryant1410 commented on _posts/2021-03-07-compose-themes.md
> +```
```suggestion
```
```

So the rendered code block just fits the code :smile:

2021-05-06 00:49 UTC, bryant1410 commented on _posts/2021-03-07-compose-themes.md
> +```
Remove this new line so the rendered code block just fits the text :sweat_smile:

2021-05-06 17:32 UTC, mtnbarreto commented on _posts/2021-03-07-compose-themes.md
> +If you have tried [Jetpack Compose], the new framework for building user interfaces for Android (and in early steps for [Desktop](https://www.jetbrains.com/lp/compose/) and [Web](https://blog.jetbrai
```suggestion
Building Android UIs with a consistent look and feel using the new [Jetpack Compose] framework it's easier than ever by setting up themes.
```

2021-05-07 00:49 UTC, mtnbarreto requested changes

2021-05-07 00:49 UTC, mtnbarreto commented on _posts/2021-03-07-compose-themes.md
> +Material theme is great, but it oftentimes lacks in that it's a bit too strict and limited on what you can and cannot do with it.
```suggestion
Compose offers an implementation of the Material design that makes it easy to use Material style throughout the whole app just by adding few lines of code. As you may already know, Material theme allows us to have a consistent and uniform UI that follows Android UI best practices and guidelines, but at the same time, it's super rigid and limited when the app needs a more complex UI customization level.
```

2021-05-07 00:49 UTC, mtnbarreto commented on _posts/2021-03-07-compose-themes.md
> +In this post, we'll not talk about how can you apply the Material theme in your app, we'll analyze how to adapt, customize, extend and make Material Theme more flexible so that it can stick to your p
```suggestion
In this post, we'll learn how to adapt, customize and extend Compose Material Theme in order to fulfill your app UI requirement and get rid of material limitations. 
```

2021-05-07 00:49 UTC, mtnbarreto commented on _posts/2021-03-07-compose-themes.md
> +The definition is not complex.
```suggestion
```

2021-05-07 00:49 UTC, mtnbarreto commented on _posts/2021-03-07-compose-themes.md
> +More information can be found in [Android's themes documentation], but themes assign semantic names such as `colorPrimary` to Android resources, that can be later used as references in different plac
```suggestion
[Android Theme] is just a collection of resources that are useful throughout a given application. Each resource has a semantic name such as `colorPrimary` that can be used as references from different places on the app.
```

2021-05-07 00:49 UTC, mtnbarreto commented on _posts/2021-03-07-compose-themes.md
> +Most Android applications already follow (or should be following) [Material Design Guidelines], and that's why Material created `MaterialTheme`.
```suggestion
Most Android apps already follow [Material Design Guidelines], and that's the reason Android SDK already provides the `MaterialTheme` for Compose apps.
```

2021-05-07 00:49 UTC, mtnbarreto commented on _posts/2021-03-07-compose-themes.md
> +Material does a great job, but from my point of view, it lacks flexibility.
```suggestion
Material does a great job making sure every app follows android UI guidelines, but it clearly lacks flexibility.
```

2021-05-07 00:49 UTC, mtnbarreto commented on _posts/2021-03-07-compose-themes.md
> +So, here lies the **first problem**: you have to adapt your look and feel to the Material guidelines, and if you don't, then it becomes hard to use it.
So, here lies the **first problem**: Material theme by itself it's not flexible enough to build complex app look and feels.

2021-05-07 00:49 UTC, mtnbarreto commented on _posts/2021-03-07-compose-themes.md
> +The **second issue** is that Material comprises only [color], [typography], and [shape] attributes, but what if we want to define more resources in a theme, such as dimensions or icons?
```suggestion
Secondly, Material comprises only [color], [typography], and [shape] attributes, but what if your app needs more resources, such as dimensions or icons?
```

2021-05-07 00:49 UTC, mtnbarreto commented on _posts/2021-03-07-compose-themes.md
> +It's a class that defines the 9 main Material colors, and it also provides two functions to define both the light and dark color sets.
```suggestion
Compose provides the [`Colors`] class to model the [Material color system] which includes nine colors and two functions to define light and dark color sets.
```

2021-05-07 00:49 UTC, mtnbarreto commented on _posts/2021-03-07-compose-themes.md
> +In my experience, 9 colors are not enough, as design teams usually define many more.
```suggestion
According to our experience, most apps need way more than 9 colors.
```

2021-05-07 00:49 UTC, mtnbarreto commented on _posts/2021-03-07-compose-themes.md
> +In my experience, 9 colors are not enough, as design teams usually define many more.
El `as design teams usually define many more.` es un detalle que se puede omitir, en mi opinipn no aporta nada.

2021-05-07 00:49 UTC, mtnbarreto commented on _posts/2021-03-07-compose-themes.md
> +Remember, a theme is a semantic resource set, so we could also have dimensions, icons, or any other resource that will be used in the app.
```suggestion
Remember, a theme is a semantic resource set, so we could also need dimensions, icons, or any other resource to build the custom app UI.
```

2021-05-07 00:49 UTC, mtnbarreto commented on _posts/2021-03-07-compose-themes.md
> +I usually define dimensions in my theme since many of them have a meaning for me.
No me gusta el uso de `I`, por momentos es poco inclusivo con el equipo.

2021-05-07 00:49 UTC, mtnbarreto commented on _posts/2021-03-07-compose-themes.md
> +In the previous section, we learned how to extend the properties provided by Material, but what if we wanted to define new ones?
```suggestion
So far, we've learned how to extend the properties provided by Material, but what if we wanted to define new ones?
```

2021-05-07 13:12 UTC, mirland commented on _posts/2021-03-07-compose-themes.md
> +Material theme is great, but it oftentimes lacks in that it's a bit too strict and limited on what you can and cannot do with it.
I don't like the idea of losing the info that here we will not explain how to use the material theme, it's something that you should read before this blog. I think it's important

2021-05-07 13:18 UTC, mirland commented on _posts/2021-03-07-compose-themes.md
> +Most Android applications already follow (or should be following) [Material Design Guidelines], and that's why Material created `MaterialTheme`.
it's not the android sdk... it super confusing 
```suggestion
Most Android apps already follow [Material Design Guidelines], and that's the reason Jetpack Compose already provides the `MaterialTheme` for Compose apps.
```

2021-05-07 13:23 UTC, mirland commented on _posts/2021-03-07-compose-themes.md
> +So, here lies the **first problem**: you have to adapt your look and feel to the Material guidelines, and if you don't, then it becomes hard to use it.
if we don't use bold in the next sentence, we should remove it here too
```suggestion
So, here lies the first problem: you have to adapt your look and feel to the Material guidelines, and if you don't, then it becomes hard to use it.
```

2021-05-07 13:27 UTC, mirland commented on _posts/2021-03-07-compose-themes.md
> +I usually define dimensions in my theme since many of them have a meaning for me.
maybe: 
```suggestion
Dimensions are something that we usually define in our theme since many of them have a meaning in our app context.
```

2021-05-07 14:10 UTC, mirland commented on _posts/2021-03-07-compose-themes.md
> +Material theme is great, but it oftentimes lacks in that it's a bit too strict and limited on what you can and cannot do with it.
```suggestion
Compose offers an implementation of the Material design that makes it easy to use Material style throughout the whole app just by adding few lines of code.
If you haven't tried it, you can check out [Android's documentation](https://developer.android.com/jetpack/compose/themes).
As you may already know, Material theme allows us to have a consistent and uniform UI that follows Android UI best practices and guidelines, but at the same time, it's super rigid and limited when the app needs a more complex UI customization level.
```

2021-05-07 16:55 UTC, mtnbarreto commented on _posts/2021-05-07-compose-themes.md
> +You can read more about Compose themes at the [official documentation](https://developer.android.com/jetpack/compose/themes).
```suggestion
Compose offers an implementation of the Material design that makes it easy to use Material style throughout the whole app. 
```

2021-05-07 16:55 UTC, mtnbarreto commented on _posts/2021-05-07-compose-themes.md
> +Building Android UIs with a consistent look and feel is easier than ever by using the new [Jetpack Compose] framework and setting up themes.
```suggestion
Building Android UIs with a consistent look and feel is easier than ever by using the new [Jetpack Compose] framework and setting up [themes](https://developer.android.com/jetpack/compose/themes).
```

2021-05-07 16:56 UTC, mtnbarreto commented on _posts/2021-05-07-compose-themes.md
> +As you may already know, Material theme allows us to have a consistent and uniform UI that follows Android UI best practices and guidelines, but at the same time, it's super rigid and limited when th
```suggestion
As you may already know, Material allows us to have a consistent and uniform UI that follows Android UI best practices and guidelines, but at the same time, it's super rigid and limited when the app needs a more complex UI customization level.
```

2021-05-07 16:58 UTC, mtnbarreto commented on _posts/2021-05-07-compose-themes.md
> +Most Android apps already follow [Material Design Guidelines], and that's the reason Jetpack Compose already provides the `MaterialTheme` for Compose apps.
```suggestion
Most Android apps already follow [Material Design Guidelines], and that's the reason Jetpack Compose provides the `MaterialTheme` for Compose apps by default.
```

2021-05-07 16:58 UTC, mtnbarreto commented on _posts/2021-05-07-compose-themes.md
> +It's a systematic way to customize Material Design to better reflect your product’s design needs.
```suggestion
```

2021-05-07 16:59 UTC, mtnbarreto commented on _posts/2021-05-07-compose-themes.md
> +Material does a great job making sure every app follows android UI guidelines, but it clearly lacks flexibility.
```suggestion
Material does a great job making sure every app follows Android UI guidelines, but it clearly lacks flexibility.
```

2021-05-07 17:52 UTC, mtnbarreto commented on _posts/2021-05-07-compose-themes.md
> +Secondly, Material comprises only [color], [typography], and [shape] attributes, but what if your app needs more resources, such as dimensions or icons?
```suggestion
So, here lies the first problem: you have to adapt your look and feel to the Material guidelines, and if you don't, then it becomes hard to use it.

Secondly, Material comprises only [color], [typography], and [shape] attributes, but what if your app needs more resources, such as dimensions or icons?
```

2021-05-07 17:57 UTC, mtnbarreto commented on _posts/2021-05-07-compose-themes.md
> +It's a systematic way to customize Material Design to better reflect your product’s design needs.
```suggestion
Most Android apps already follow [Material Design Guidelines], that's the reason Jetpack Compose provides the `MaterialTheme` implementation for Compose apps, which is a systematic way to customize Material Design to better reflect your app style and branding.
```

2021-05-07 18:02 UTC, mtnbarreto commented on _posts/2021-05-07-compose-themes.md
> +However, we saw that Material themes lack flexibility, and if designers don't stick 100% to their guidelines, you may be in trouble as you will have to maintain many separate theme components not han
```suggestion
Themes allow for consistency throughout an application, especially if you define it at the beginning, just by applying minor configurations.

However, we saw that Material themes lack flexibility, and if designers don't stick 100% to their guidelines, you may be in trouble as you will have to maintain many separate theme components not handled directly by your app theme.
```

2021-05-07 18:03 UTC, mtnbarreto commented on _posts/2021-05-07-compose-themes.md
> +Last but not least, you avoid magic numbers making your codebase more maintainable and readable.
```suggestion
That's all fine, but you may be asking yourself a question which is: what are the actual advantages?

First, your theme will be consistent.
You can reuse the dimensions in multiple places throughout your app and thus make sure the correct values are enforced.

Second, you gain flexibility as you can define custom dimensions based on the device's state or specs.
A practical example, considering devices with small screens, is to define a separate set of dimensions for them to improve the user experience.

Last but not least, you avoid magic numbers making your codebase more maintainable and readable.
```

2021-05-07 18:18 UTC, mtnbarreto commented on _posts/2021-05-07-compose-themes.md
> +The code in this blog should be useful for most applications, but I recommend you check out [the full implementation on GitHub](https://github.com/xmartlabs/gong/tree/b0b617e/app/src/main/java/com/xm
```suggestion

In this post, we teach you how to overcome all these issues by extending the Material theme while making it flexible to adapt it to your product.
```

2021-05-07 20:49 UTC, mtnbarreto commented on _posts/2021-05-07-compose-themes.md
> +As you may already know, Material allows us to have a consistent and uniform UI that follows Android UI best practices and guidelines, but at the same time, it's super rigid and limited when the app
```suggestion
As you may already know, Material allows us to have a uniform UI that follows Android UI best practices and guidelines, but at the same time, it's super rigid and limited when the app needs a more complex UI customization level.
```

2021-05-07 20:50 UTC, mtnbarreto commented on _posts/2021-05-07-compose-themes.md
> +In this post, we'll learn how to adapt, customize and extend Compose Material Theme in order to fulfill your app UI requirement and get rid of material limitations.
```suggestion
In this post, we'll learn how to adapt, customize and extend Compose Material Theme in order to fulfill your app UI requirements and get rid of material limitations. 
```

2021-05-07 20:54 UTC, mtnbarreto commented on _posts/2021-05-07-compose-themes.md
> +Material has some guides to help improve it and also allows you to be consistent with other apps on the same platform.
```suggestion
Material helps in that regard by ensuring every Android app follows Android's UI practices and its overall guidelines. 
```

2021-05-07 20:56 UTC, mtnbarreto approved these changes

2021-05-07 21:07 UTC, mtnbarreto commented on _posts/2021-05-07-compose-themes.md
> +Themes allow for consistency throughout an application, especially if you define it at the beginning, just by applying minor configurations.
```suggestion
Themes allow consistency throughout your application, especially if it's configured at the beginning of the app development.
```

2021-05-10 22:35 UTC, bryant1410 commented on _posts/2021-05-10-compose-themes.md
> +In this blog post, we present concepts and ideas to leverage compose, app theming, and Material and if your app still needs more customization, be able to extend material capabilities.
I think it's clearer this way:

```suggestion
This blog post presents concepts and ideas to leverage compose, app theming, and Material. If your app still needs more customization, you'll be able to extend Material capabilities.
```

2021-05-10 22:59 UTC, mirland commented on _posts/2021-05-10-compose-themes.md
> +In this blog post, we present concepts and ideas to leverage compose, app theming, and Material and if your app still needs more customization, be able to extend material capabilities.
Maybe?
```suggestion
This blog post presents concepts and ideas to leverage compose, app theming, and Material.
If your app still needs more customization, you'll be able to extend Material capabilities to derive full benefit from them.
```

2021-05-11 16:38 UTC, merged