WIP: iOS performance speedup with Bender and MPS
xmartlabs/blog pull request #163
Opened 2021-08-23 12:31 UTC by mats-claassen

Please review:
* Should I mention DreamSnap or not?
* Conclusions and CTA
* Title suggestions welcome
* Should I go into more detail at some point
* Presentation of benchmark results

2021-08-23 13:13 UTC, bryant1410 reviewed
I didn't read it, just looked at it superficially. I think it'd be good to show the benchmark results on a bar/line plot. It's visually clearer and easier to understand the difference.

2021-08-23 13:15 UTC, bryant1410 commented
Also, what if converting the section "So which framework should I choose?" into a list of bullet points of "when to choose bender" and "when to choose Core ML"? So it's like a reference that people come back to read again at other times. Having it as bullet points helps with this goal.

2021-08-24 15:32 UTC, mtnbarreto commented
> I didn't read it, just looked at it superficially. I think it'd be good to show the benchmark results on a bar/line plot. It's visually clearer and easier to understand the difference.

agreed! we can manage this with the design team (pesto).

2021-08-24 18:03 UTC, renzodgc commented on _posts/2021-08-30-bender-is-the-best.md
> +If you need help doing such a conversion feel free to reach out at [hi@xmartlabs.com](mailto:hi@xmartlabs.com)
```suggestion
That being said we created Bender back then to have a friendlier interface to MPS, if you need help doing such a conversion feel free to reach out at [hi@xmartlabs.com](mailto:hi@xmartlabs.com).
```

2021-08-24 20:45 UTC, pgrill commented on _posts/2021-08-30-bender-is-the-best.md
> +Now we decided we wanted to update the app with newer models and found a Magenta model hosted on [TFHub].
Maybe we can include a short description of what Magenta is?

2021-08-24 21:54 UTC, mtnbarreto requested changes

2021-08-30 21:24 UTC, merged